files:
  index: resources/views/components/ui/tab/index.blade.php
  group: resources/views/components/ui/tab/group.blade.php
  panel: resources/views/components/ui/tab/panel.blade.php
  tabs:  resources/views/components/ui/tabs.blade.php
dependencies: [button]