files:
  index: resources/views/components/ui/autocomplete/index.blade.php
  items: resources/views/components/ui/autocomplete/items.blade.php
  item:  resources/views/components/ui/autocomplete/item.blade.php

dependencies:
  internal: [icon]
  helpers: [popup]