files:
  index: resources/views/components/ui/otp/index.blade.php
  input: resources/views/components/ui/otp/input.blade.php
  separator: resources/views/components/ui/otp/separator.blade.php
dependencies:
  internal: [separator]
