files:
  index: resources/views/components/ui/accordion/index.blade.php
  item: resources/views/components/ui/accordion/item.blade.php
  trigger: resources/views/components/ui/accordion/trigger.blade.php
  content: resources/views/components/ui/accordion/content.blade.php