files:
  index: resources/views/components/ui/dropdown/index.blade.php
  item: resources/views/components/ui/dropdown/item.blade.php
  submenu: resources/views/components/ui/dropdown/submenu.blade.php
  group: resources/views/components/ui/dropdown/group.blade.php
  separator: resources/views/components/ui/dropdown/separator.blade.php